[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
drift_v1 = "Do3SKatkSNF3FjKHpeMthHqTE5JfAJzTCrCC8xNBnkGP"
mock_usdc_faucet = "BCuwrSaZemz7PVtDxruKT1S8HBHhBFixw6r4AsFimqr3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
